version: '3'
services:
  py-app-01:
    build: .
    container_name: py-app-01
    # Flask uses port 5000, but so does Docker registry, so we use another one
    ports:
     - "3001:5000"
    links:
      - redis:redis 

  py-app-02:
    build: .
    container_name: py-app-02
    # Flask uses port 5000, but so does Docker registry, so we use another one
    ports:
     - "3002:5000"
    links:
      - redis:redis 

  redis:
    image: "redis:alpine"

  ngnx:
      build: ngnx/.
      container_name: ngnx-py-redis
      links:
       - py-app-01:py-app-01
       - py-app-02:py-app-02
      ports:
       - "80:80"
       - "443:443"
       - "8081:8081"
    
